config/routes.rb
MobileApi::Application.routes.draw do
  resources :offers

  root :to => 'offers#index'

end

app/models/offer.rb
class Offer
  attr_accessor :title, :payout, :thumbnail

  def initialize params = {}
    @title     = params[:title]
    @payout    = params[:payout]
    @thumbnail = params[:thumbnail]
  end
end

app/models/offer_api.rb
class OfferApi
  def initialize(params = {})
    @params         = params
    @request_params = params.reverse_merge(OfferApi.config)
    @request_params.delete :api_key
  end

  def load_offers
    return [] if @params.empty?
    request["offers"].map(&:symbolize_keys).map do |offer|
      Offer.new(offer)
    end
  end

  def self.load_offers(params)
    OfferApi.new(params).load_offers
  end

  def self.config
    config_hash = YAML.load(File.open(File.expand_path('../../../config/offer_api.yml',  __FILE__)))
    config_hash["offer_api"].symbolize_keys
  end

  private

  def request
    response = HTTParty.get(request_url)
    validate(response)
    response
  end

  def validate(response)
    unless check_response(response)
      raise OfferApi::BadSignatureException
    end
  end

  def check_response(response)
    response.headers["x-sponsorpay-response-signature"] == Digest::SHA1.hexdigest(response.body + OfferApi.config[:api_key])
  end

  def request_url
    OfferApi::Params.new(@request_params, OfferApi.config[:api_key]).generate_api_url
  end

  class BadSignatureException < Exception; end
end

app/models/offer_api/params.rb
class OfferApi
  class Params
    def initialize params, api_key
      @params  = params.reverse_merge :timestamp => Time.now.to_i
      @api_key = api_key
    end

    def generate_hash 
      params = @params.sort 
      params = convert_array_to_string(params)
      params = params + "&#{@api_key}"

      Digest::SHA1.hexdigest(params)
    end

    def generate_api_url 
      params = @params.merge :hashkey => generate_hash 
      params = convert_array_to_string(params)
      
      "http://api.sponsorpay.com/feed/v1/offers.json?#{params}"
    end

    private

    def convert_array_to_string params
      params = params.map { |pair| "#{pair[0]}=#{pair[1]}" }

      params.join("&")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = OfferApi.load_offers((params[:offer] || {}).symbolize_keys)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MobileApi
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .wrapper
      %h1 Ruby developer challenge
      #content
        = yield

app/views/offers/_offer.html.haml
.offer
  .offer-title
    = offer.title
  .offer-payout
    = offer.payout
  .offer-thumbnail
    = image_tag(offer.thumbnail["hires"])

app/views/offers/_search_form.html.haml
= semantic_form_for :offer, :url => offers_path, :method => :get do |f|
  = f.inputs :name => "Form options" do
    = f.input :uid
    = f.input :pub0
    = f.input :page
    = f.actions do
      = f.action :submit, :label => "Submit"

app/views/offers/index.html.haml
#search_form_section.section
  = render "search_form"
#offers_section.section
  - @offers.each do |offer|
    = render "offer", :offer => offer
  - if @offers.empty? 
    .no_offers 
      No offers